services:
  postgres-data:
    image: postgres:15
    container_name: postgres-data
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: football_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    networks:
      - airflow

volumes:
  postgres-data-volume:
